import { useEffect, useState } from "react";
import { readableError } from "../lib/workspace";
import { Modal } from "./Modal";
import { assignSpaceChannel, createSpaceCategory, deleteSpaceCategory, kickSpaceMember, loadSpaceManagement, manageSpaceMember, renameSpaceCategory, renameSpaceChannel, reorderSpaceCategory, reorderSpaceChannel, revokeSpaceInvite, setSpaceBan, setConversationSendPermission, type SpaceMember } from "../lib/space-management";
import "../space-management.css";
type Props = { spaceId: string; currentUserId: string; onChanged: () => void; onClose: () => void };
type Tab = "channels" | "members" | "invites" | "bans";
export function SpaceManagement({ spaceId, currentUserId, onChanged, onClose }: Props) {
  const [tab, setTab] = useState<Tab>("channels"); const [state, setState] = useState<Awaited<ReturnType<typeof loadSpaceManagement>> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = async () => { try { setState(await loadSpaceManagement(spaceId)); } catch (e) { setError(readableError(e)); } };
  useEffect(() => { void refresh(); }, [spaceId]);
  async function act(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); await refresh(); onChanged(); } catch (e) { setError(readableError(e)); } finally { setBusy(false); } }
  return <Modal title="Gestisci spazio" description="Canali, membri e inviti" onClose={onClose} className="space-management"><nav className="space-management-tabs">{(["channels", "members", "invites", "bans"] as Tab[]).map((name) => <button type="button" disabled={busy} key={name} className={tab === name ? "active" : ""} onClick={() => setTab(name)}>{name === "channels" ? "Canali" : name === "members" ? "Membri" : name === "invites" ? "Inviti" : "Ban"}</button>)}</nav>{error && <p role="alert" className="space-management-error">{error}</p>}{!state ? <p>Caricamento…</p> : state.members.find(member=>member.user_id===currentUserId)?.role === "member" ? <p>La gestione del server è riservata agli amministratori.</p> : tab === "channels" ? <Channels state={state} busy={busy} spaceId={spaceId} act={act} /> : tab === "members" ? <Members spaceId={spaceId} members={state.members} currentUserId={currentUserId} busy={busy} act={act} /> : tab === "invites" ? <div className="space-management-list">{state.invites.map((i) => <div className="space-management-row" key={i.id}><span>{i.use_count}/{i.max_uses}</span>{!i.revoked_at && <button type="button" disabled={busy} onClick={() => act(() => revokeSpaceInvite(i.id))}>Revoca</button>}</div>)}</div> : <div className="space-management-list">{state.bans.map((b) => <div className="space-management-row" key={b.user_id}><span>{b.user_id}</span><button type="button" disabled={busy} onClick={() => act(() => setSpaceBan(spaceId, b.user_id, false))}>Rimuovi ban</button></div>)}</div>}</Modal>;
}
function InlineRename({ value, busy, onSave }: { value: string; busy: boolean; onSave: (name: string) => Promise<unknown> }) { const [name, setName] = useState(value); return <><input aria-label="Nome" value={name} disabled={busy} onChange={(e) => setName(e.target.value)} /><button type="button" disabled={busy || !name.trim()} onClick={() => void onSave(name)}>Salva</button></>; }
function Channels({ state, spaceId, busy, act }: { state: Awaited<ReturnType<typeof loadSpaceManagement>>; spaceId: string; busy: boolean; act: (a: () => Promise<unknown>) => Promise<void> }) { const [newCategory, setNewCategory] = useState(""); return <div className="space-management-list"><div className="space-management-row"><input value={newCategory} onChange={(e) => setNewCategory(e.target.value)} placeholder="Nuova categoria" /><button type="button" disabled={busy || !newCategory.trim()} onClick={() => act(async () => { await createSpaceCategory(spaceId, newCategory); setNewCategory(""); })}>Crea</button></div>{state.categories.map((c, index) => <div className="space-management-row" key={c.id}><span>{c.name}</span><InlineRename value={c.name} busy={busy} onSave={(name) => act(() => renameSpaceCategory(c.id, name))} /><button type="button" disabled={busy} onClick={() => act(() => deleteSpaceCategory(c.id))}>Elimina</button><button type="button" disabled={busy || index === 0} onClick={() => act(() => reorderSpaceCategory(c.id, state.categories[index-1].position))}>↑</button></div>)}{state.channels.filter(c=>c.kind === "channel").map((c, index, textChannels) => <div className="space-management-row" key={c.id}><span>#{c.name}</span><select value={c.category_id ?? ""} disabled={busy} onChange={(e) => act(() => assignSpaceChannel(c.id, e.target.value || null, c.position))}><option value="">Senza categoria</option>{state.categories.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={c.send_permission} disabled={busy} onChange={(e) => act(() => setConversationSendPermission(c.id, e.target.value as "members" | "admins"))}><option value="members">Membri</option><option value="admins">Admin</option></select><InlineRename value={c.name} busy={busy} onSave={(name) => act(() => renameSpaceChannel(c.id, name))}/><button type="button" disabled={busy || index === 0} onClick={() => act(() => reorderSpaceChannel(c.id, textChannels[index-1].position, c.category_id))}>↑</button></div>)}</div>; }
function Members({ members, currentUserId, spaceId, busy, act }: { members: SpaceMember[]; currentUserId: string; spaceId: string; busy: boolean; act: (a: () => Promise<unknown>) => Promise<void> }) { const actor = members.find((m) => m.user_id === currentUserId); if (!actor || actor.role === "member") return <p>Solo owner e admin possono gestire i membri.</p>; return <div className="space-management-list">{members.map((m) => <div className="space-management-row" key={m.user_id}><span>{m.display_name || m.username} · {m.role}</span>{m.user_id !== currentUserId && m.role !== "owner" && (actor.role === "owner" || m.role === "member") && <><select disabled={busy} value={m.role} onChange={(e) => act(() => manageSpaceMember(spaceId, m.user_id, e.target.value as "member" | "admin"))}><option value="member">Membro</option>{actor.role === "owner" && <option value="admin">Admin</option>}</select><button type="button" disabled={busy} onClick={() => act(() => kickSpaceMember(spaceId, m.user_id))}>Espelli</button><button type="button" disabled={busy} onClick={() => act(() => setSpaceBan(spaceId, m.user_id, true))}>Banna</button></>}</div>)}</div>; }
